/**:
  ros__parameters:
    # Fixed parameters loaded on startup
    footprint_length_front: 0.3
    footprint_length_back: 0.2
    footprint_width: 0.3

    # Dynamic parameters
    deceleration: 0.2

    distance_buffer: 0.1
