/**:
  ros__parameters:
    use_sim_time: true

    # Fixed parameters loaded on startup
    deceleration_linear: 0.2
    deceleration_angular: 0.5

    footprint_length_front: 0.3
    footprint_length_back: 0.2
    footprint_width: 0.3

    # Dynamic parameters
    distance_buffer: 0.2
